<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.13" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.13" />
    <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="8.0.13" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\gesFactu.Application\gesFactu.Application.csproj" />
    <ProjectReference Include="..\Core\gesFactu.Domain\gesFactu.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\VERIFACTU\*.xsd.xml">
      <Link>VERIFACTU\%(Filename)%(Extension)</Link>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
