// <auto-generated />
using System;
using gesFactu.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace gesFactu.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("gesFactu.Domain.Entities.BillingRecord", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<string>("AeatSubmissionId").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<int?>("CancelsBillingRecordId").HasColumnType("integer");
                    b.Property<string>("ComputedHash").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<DateTime?>("CreateDate").ValueGeneratedOnAdd().HasColumnType("timestamp with time zone").HasDefaultValueSql("CURRENT_TIMESTAMP");
                    b.Property<string>("CreatedBy").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<DateTime?>("DeletedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("DeletedBy").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<string>("Description").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<string>("FiscalInvoiceNumber").IsRequired().HasMaxLength(60).HasColumnType("character varying(60)");
                    b.Property<string>("InvoiceNumber").IsRequired().HasMaxLength(60).HasColumnType("character varying(60)");
                    b.Property<string>("InvoiceSeries").IsRequired().HasMaxLength(60).HasColumnType("character varying(60)");
                    b.Property<string>("InvoiceType").IsRequired().ValueGeneratedOnAdd().HasMaxLength(2).HasColumnType("character varying(2)").HasDefaultValue("F1");
                    b.Property<bool>("IsDeleted").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(false);
                    b.Property<bool>("IsSubmitted").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(false);
                    b.Property<DateOnly>("IssueDate").HasColumnType("date");
                    b.Property<string>("IssuerName").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                    b.Property<string>("IssuerNif").IsRequired().HasMaxLength(9).HasColumnType("character varying(9)");
                    b.Property<string>("LastModifiedBy").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<DateTime?>("LastModifiedDate").HasColumnType("timestamp with time zone");
                    b.Property<int?>("PreviousBillingRecordId").HasColumnType("integer");
                    b.Property<decimal?>("RectifiedBaseAmount").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                    b.Property<decimal?>("RectifiedSurchargeAmount").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                    b.Property<decimal?>("RectifiedTaxAmount").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                    b.Property<string>("RectificationType").HasMaxLength(1).HasColumnType("character varying(1)");
                    b.Property<int?>("RectifiesBillingRecordId").HasColumnType("integer");
                    b.Property<int?>("SubsanatesBillingRecordId").HasColumnType("integer");
                    b.Property<string>("PreviousRecordHash").HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<string>("RecipientName").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                    b.Property<string>("RecipientNif").IsRequired().HasMaxLength(9).HasColumnType("character varying(9)");
                    b.Property<string>("RecordType").IsRequired().ValueGeneratedOnAdd().HasMaxLength(16).HasColumnType("character varying(16)").HasDefaultValue("Alta");
                    b.Property<string>("RegisterTimestamp").IsRequired().HasMaxLength(25).HasColumnType("character varying(25)");
                    b.Property<Guid?>("SubmissionCorrelationId").HasColumnType("uuid");
                    b.Property<string>("Status").IsRequired().ValueGeneratedOnAdd().HasMaxLength(50).HasColumnType("character varying(50)").HasDefaultValue("Pendiente");
                    b.Property<decimal>("TotalAmount").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                    b.Property<decimal>("TotalTaxAmount").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                    b.HasKey("Id");
                    b.HasIndex("CancelsBillingRecordId").HasDatabaseName("IX_BillingRecords_CancelsBillingRecordId");
                    b.HasIndex("PreviousBillingRecordId").HasDatabaseName("IX_BillingRecords_PreviousBillingRecordId");
                    b.HasIndex("RectifiesBillingRecordId").HasDatabaseName("IX_BillingRecords_RectifiesBillingRecordId");
                    b.HasIndex("SubsanatesBillingRecordId").HasDatabaseName("IX_BillingRecords_SubsanatesBillingRecordId");
                    b.HasIndex("IssuerNif", "Id").HasDatabaseName("IX_BillingRecords_Issuer_GenerationOrder");
                    b.HasIndex("IssuerNif", "FiscalInvoiceNumber", "IssueDate").IsUnique().HasFilter("\"RecordType\" = 'Alta' AND \"SubsanatesBillingRecordId\" IS NULL").HasDatabaseName("UX_BillingRecords_FiscalIdentity");
                    b.ToTable("BillingRecords", (string)null);
                });

            modelBuilder.Entity("gesFactu.Domain.Entities.BillingTaxDetail", b =>
                {
                    b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("integer");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));
                    b.Property<int>("BillingRecordId").HasColumnType("integer");
                    b.Property<DateTime?>("CreateDate").ValueGeneratedOnAdd().HasColumnType("timestamp with time zone").HasDefaultValueSql("CURRENT_TIMESTAMP");
                    b.Property<string>("CreatedBy").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<DateTime?>("DeletedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("DeletedBy").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<decimal?>("EquivalenceSurchargeAmount").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                    b.Property<decimal?>("EquivalenceSurchargeRate").HasPrecision(5, 2).HasColumnType("numeric(5,2)");
                    b.Property<string>("ExemptionCause").HasMaxLength(2).HasColumnType("character varying(2)");
                    b.Property<DateTime?>("LastModifiedDate").HasColumnType("timestamp with time zone");
                    b.Property<string>("LastModifiedBy").HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<bool>("IsDeleted").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(false);
                    b.Property<string>("OperationQualification").HasMaxLength(2).HasColumnType("character varying(2)");
                    b.Property<string>("RegimeCode").HasMaxLength(2).HasColumnType("character varying(2)");
                    b.Property<decimal?>("TaxAmount").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                    b.Property<decimal>("TaxBase").HasPrecision(18, 2).HasColumnType("numeric(18,2)");
                    b.Property<string>("TaxCode").HasMaxLength(2).HasColumnType("character varying(2)");
                    b.Property<decimal?>("TaxRate").HasPrecision(5, 2).HasColumnType("numeric(5,2)");
                    b.HasKey("Id");
                    b.HasIndex("BillingRecordId", "Id").HasDatabaseName("IX_BillingTaxDetails_Record_Order");
                    b.ToTable("BillingTaxDetails", (string)null);
                });

            modelBuilder.Entity("gesFactu.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid");
                    b.Property<string>("Action").IsRequired().HasMaxLength(32).HasColumnType("character varying(32)");
                    b.Property<string>("Actor").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
                    b.Property<string>("CorrelationId").HasMaxLength(128).HasColumnType("character varying(128)");
                    b.Property<string>("EntityId").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("EntityName").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("NewValues").HasColumnType("jsonb");
                    b.Property<DateTime>("OccurredAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("OldValues").HasColumnType("jsonb");
                    b.HasKey("Id");
                    b.HasIndex("CorrelationId").HasDatabaseName("IX_AuditLogs_CorrelationId");
                    b.HasIndex("EntityName", "EntityId", "OccurredAtUtc").HasDatabaseName("IX_AuditLogs_Entity_Time");
                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("gesFactu.Domain.Entities.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uuid");
                    b.Property<DateTime?>("CompletedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<DateTime>("CreatedAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<DateTime>("ExpiresAtUtc").HasColumnType("timestamp with time zone");
                    b.Property<string>("Key").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("Method").IsRequired().HasMaxLength(16).HasColumnType("character varying(16)");
                    b.Property<string>("Path").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<string>("RequestHash").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
                    b.Property<string>("ResponseBody").HasColumnType("text");
                    b.Property<string>("ResponseContentType").HasMaxLength(200).HasColumnType("character varying(200)");
                    b.Property<string>("ResponseLocation").HasMaxLength(1000).HasColumnType("character varying(1000)");
                    b.Property<int?>("ResponseStatusCode").HasColumnType("integer");
                    b.Property<string>("Status").IsRequired().HasMaxLength(16).HasColumnType("character varying(16)");
                    b.HasKey("Id");
                    b.HasIndex("ExpiresAtUtc").HasDatabaseName("IX_IdempotencyRecords_ExpiresAt");
                    b.HasIndex("Key", "Method", "Path").IsUnique().HasDatabaseName("UX_IdempotencyRecords_Key_Method_Path");
                    b.ToTable("IdempotencyRecords", (string)null);
                });

            modelBuilder.Entity("gesFactu.Domain.Entities.DeadLetterMessage", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("CorrelationId").IsRequired().HasMaxLength(36).HasColumnType("character varying(36)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("FailureReason").IsRequired().HasMaxLength(1000).HasColumnType("character varying(1000)");
                    b.Property<bool>("IsReviewed").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(false);
                    b.Property<string>("LastErrorResponse").HasColumnType("text");
                    b.Property<DateTime>("MovedToDlqAt").HasColumnType("timestamp with time zone");
                    b.Property<long>("OriginalMessageId").HasColumnType("bigint");
                    b.Property<string>("Payload").IsRequired().HasColumnType("text");
                    b.Property<int>("ProcessingAttempts").HasColumnType("integer");
                    b.Property<string>("ReviewNotes").HasMaxLength(2000).HasColumnType("character varying(2000)");
                    b.HasKey("Id");
                    b.HasIndex("CorrelationId").IsUnique().HasDatabaseName("IX_DeadLetterMessages_CorrelationId");
                    b.HasIndex("IsReviewed", "MovedToDlqAt").HasDatabaseName("IX_DeadLetterMessages_UnreviewedByDate");
                    b.ToTable("DeadLetterMessages", (string)null);
                });

            modelBuilder.Entity("gesFactu.Domain.Entities.OutboxMessage", b =>
                {
                    b.Property<long>("Id").ValueGeneratedOnAdd().HasColumnType("bigint");
                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));
                    b.Property<int>("AggregateId").HasColumnType("integer");
                    b.Property<string>("AggregateType").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                    b.Property<Guid>("CorrelationId").HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").ValueGeneratedOnAdd().HasColumnType("timestamp with time zone").HasDefaultValueSql("CURRENT_TIMESTAMP");
                    b.Property<string>("EventType").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                    b.Property<bool>("IsProcessed").ValueGeneratedOnAdd().HasColumnType("boolean").HasDefaultValue(false);
                    b.Property<string>("LastProcessingError").HasColumnType("text");
                    b.Property<string>("LockedBy").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<DateTime?>("LockedUntil").HasColumnType("timestamp with time zone");
                    b.Property<DateTime?>("NextAttemptAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Payload").IsRequired().HasColumnType("text");
                    b.Property<DateTime?>("ProcessedAt").HasColumnType("timestamp with time zone");
                    b.Property<int>("ProcessingAttempts").ValueGeneratedOnAdd().HasColumnType("integer").HasDefaultValue(0);
                    b.HasKey("Id");
                    b.HasIndex("AggregateId").HasDatabaseName("IX_OutboxMessages_AggregateId");
                    b.HasIndex("CorrelationId").IsUnique().HasDatabaseName("IX_OutboxMessages_CorrelationId");
                    b.HasIndex("IsProcessed").HasDatabaseName("IX_OutboxMessages_IsProcessed");
                    b.HasIndex("AggregateType", "AggregateId", "EventType").IsUnique().HasDatabaseName("UX_OutboxMessages_AggregateEvent");
                    b.HasIndex("IsProcessed", "NextAttemptAt", "LockedUntil", "CreatedAt").HasDatabaseName("IX_OutboxMessages_Claim");
                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("gesFactu.Domain.Entities.BillingTaxDetail", b =>
                {
                    b.HasOne("gesFactu.Domain.Entities.BillingRecord", "BillingRecord")
                        .WithMany("TaxDetails")
                        .HasForeignKey("BillingRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("BillingRecord");
                });

            modelBuilder.Entity("gesFactu.Domain.Entities.SubmissionAttempt", b =>
                {
                    b.Property<Guid>("Id").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("AeatSubmissionId").HasMaxLength(100).HasColumnType("character varying(100)");
                    b.Property<int>("AttemptNumber").HasColumnType("integer");
                    b.Property<int>("BillingRecordId").HasColumnType("integer");
                    b.Property<int?>("DurationMilliseconds").HasColumnType("integer");
                    b.Property<string>("Notes").HasMaxLength(1000).HasColumnType("character varying(1000)");
                    b.Property<string>("RequestPayload").IsRequired().HasColumnType("text");
                    b.Property<DateTime?>("RespondedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("ResponseCode").HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<string>("ResponseDescription").HasMaxLength(2000).HasColumnType("character varying(2000)");
                    b.Property<string>("ResponsePayload").HasColumnType("text");
                    b.Property<string>("Status").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("SubmittedAt").HasColumnType("timestamp with time zone");
                    b.HasKey("Id");
                    b.HasIndex("BillingRecordId").HasDatabaseName("IX_SubmissionAttempts_BillingRecordId");
                    b.HasIndex("BillingRecordId", "AttemptNumber").IsUnique().HasDatabaseName("UX_SubmissionAttempts_BillingRecordAndAttempt");
                    b.HasIndex("Status", "SubmittedAt").HasDatabaseName("IX_SubmissionAttempts_StatusAndTime");
                    b.ToTable("SubmissionAttempts", (string)null);
                });

            modelBuilder.Entity("gesFactu.Domain.Entities.SubmissionAttempt", b =>
                {
                    b.HasOne("gesFactu.Domain.Entities.BillingRecord", "BillingRecord")
                        .WithMany("SubmissionAttempts")
                        .HasForeignKey("BillingRecordId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                    b.Navigation("BillingRecord");
                });

            modelBuilder.Entity("gesFactu.Domain.Entities.BillingRecord", b =>
                {
                    b.Navigation("SubmissionAttempts");
                    b.Navigation("TaxDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
